/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef CONNECT4UPDATE_PRIVATE_H
#define CONNECT4UPDATE_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"6.0.4.48"
#define VER_MAJOR	6
#define VER_MINOR	0
#define VER_RELEASE	4
#define VER_BUILD	48
#define COMPANY_NAME	""
#define FILE_VERSION	"6.0.4.48"
#define FILE_DESCRIPTION	"Connect 4 Game"
#define INTERNAL_NAME	""
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	""
#define PRODUCT_NAME	""
#define PRODUCT_VERSION	"6.0.4.48"

#endif /*CONNECT4UPDATE_PRIVATE_H*/
