/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef CONNECT4_PRIVATE_H
#define CONNECT4_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"10.4.7.106"
#define VER_MAJOR	10
#define VER_MINOR	4
#define VER_RELEASE	7
#define VER_BUILD	106
#define COMPANY_NAME	""
#define FILE_VERSION	"10.4.7.106"
#define FILE_DESCRIPTION	"Connect 4 Game"
#define INTERNAL_NAME	"Connect4"
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Connect4"
#define PRODUCT_NAME	"Connect 4"
#define PRODUCT_VERSION	"10.4.7.106"

#endif /*CONNECT4_PRIVATE_H*/
