/* THIS FILE WILL BE OVERWRITTEN BY DEV-C++ */
/* DO NOT EDIT ! */

#ifndef CONNECT4_PRIVATE_H
#define CONNECT4_PRIVATE_H

/* VERSION DEFINITIONS */
#define VER_STRING	"7.1.5.72"
#define VER_MAJOR	7
#define VER_MINOR	1
#define VER_RELEASE	5
#define VER_BUILD	72
#define COMPANY_NAME	"Haoyang Qi"
#define FILE_VERSION	"7.1.5.72"
#define FILE_DESCRIPTION	"Connect 4 Game"
#define INTERNAL_NAME	"Connect4"
#define LEGAL_COPYRIGHT	""
#define LEGAL_TRADEMARKS	""
#define ORIGINAL_FILENAME	"Connect4"
#define PRODUCT_NAME	"Connect 4"
#define PRODUCT_VERSION	"7.1.5.72"

#endif /*CONNECT4_PRIVATE_H*/
